///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OSTEst recording.
    /// </summary>
    [TestModule("101fc8cc-85b6-4bc6-8281-46c450daa40b", ModuleType.Recording, 1)]
    public partial class OSTEst : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static OSTEst instance = new OSTEst();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OSTEst()
        {
            Payment_Request_Number = "FAIL";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OSTEst Instance
        {
            get { return instance; }
        }

#region Variables

        string _Payment_Request_Number;

        /// <summary>
        /// Gets or sets the value of variable Payment_Request_Number.
        /// </summary>
        [TestVariable("46479be5-06b2-48a4-93b6-9ef37f73dca1")]
        public string Payment_Request_Number
        {
            get { return _Payment_Request_Number; }
            set { _Payment_Request_Number = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 30;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.FormInlinePanelHeading.SpanTag8' at 8;9.", repo.Login1.FormInlinePanelHeading.SpanTag8Info, new RecordItemIndex(0));
            repo.Login1.FormInlinePanelHeading.SpanTag8.Click("8;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'Login1.FormInlinePanelHeading.SpanTag8' and assigning its value to variable 'Payment_Request_Number'.", repo.Login1.FormInlinePanelHeading.SpanTag8Info, new RecordItemIndex(1));
            Payment_Request_Number = repo.Login1.FormInlinePanelHeading.SpanTag8.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'Login1.FormInlinePanelHeading.NEW_FO'", repo.Login1.FormInlinePanelHeading.NEW_FOInfo, new ActionTimeout(10000), new RecordItemIndex(2));
            repo.Login1.FormInlinePanelHeading.NEW_FOInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.FormInlinePanelHeading1' at 335;32.", repo.Login1.FormInlinePanelHeading1Info, new RecordItemIndex(3));
            repo.Login1.FormInlinePanelHeading1.Click("335;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{tab 2}'.", new RecordItemIndex(4));
            Keyboard.Press("{tab 2}", 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Payment_Request_Number'.", new RecordItemIndex(5));
            Keyboard.Press(Payment_Request_Number, 100);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
