///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R1_05_HomePage_Footer_RPMAdmin_Planning recording.
    /// </summary>
    [TestModule("ab6daf9f-0b7e-47c9-a2ae-a9061b6822b2", ModuleType.Recording, 1)]
    public partial class R1_05_HomePage_Footer_RPMAdmin_Planning : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R1_05_HomePage_Footer_RPMAdmin_Planning instance = new R1_05_HomePage_Footer_RPMAdmin_Planning();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R1_05_HomePage_Footer_RPMAdmin_Planning()
        {
            RPM_Admin_WM = "Hi, Chandler Bing!";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R1_05_HomePage_Footer_RPMAdmin_Planning Instance
        {
            get { return instance; }
        }

#region Variables

        string _RPM_Admin_WM;

        /// <summary>
        /// Gets or sets the value of variable RPM_Admin_WM.
        /// </summary>
        [TestVariable("e55be45e-9b8e-4c9e-b807-499ac0d861c1")]
        public string RPM_Admin_WM
        {
            get { return _RPM_Admin_WM; }
            set { _RPM_Admin_WM = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Footer Links
            Report.Log(ReportLevel.Info, "Section", "Footer Links", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            // Footer - Planning
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Planning\r\nValidating AttributeEqual (InnerText='Planning') on item 'Login1.NgScope.Planning'.", repo.Login1.NgScope.PlanningInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Login1.NgScope.PlanningInfo, "InnerText", "Planning", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            // Footer - Programs
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Programs\r\nValidating AttributeEqual (InnerText='Programs') on item 'Login1.NgScope.Programs1'.", repo.Login1.NgScope.Programs1Info, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.Login1.NgScope.Programs1Info, "InnerText", "Programs", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            // Footer - Projects
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Projects\r\nValidating AttributeEqual (InnerText='Projects') on item 'Login1.NgScope.Projects'.", repo.Login1.NgScope.ProjectsInfo, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Login1.NgScope.ProjectsInfo, "InnerText", "Projects", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            // Footer - Programs
            Report.Log(ReportLevel.Info, "Mouse", "Footer - Programs\r\nMouse Left Click item 'Login1.NgScope.Planning' at 34;7.", repo.Login1.NgScope.PlanningInfo, new RecordItemIndex(5));
            repo.Login1.NgScope.Planning.Click("34;7");
            Delay.Milliseconds(200);
            
            // Planning Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(6));
            
            // Programs
            Report.Log(ReportLevel.Info, "Section", "Programs", new RecordItemIndex(7));
            
            // Footer - Programs
            Report.Log(ReportLevel.Info, "Mouse", "Footer - Programs\r\nMouse Left Click item 'Login1.NgScope.Programs1' at 34;7.", repo.Login1.NgScope.Programs1Info, new RecordItemIndex(8));
            repo.Login1.NgScope.Programs1.Click("34;7");
            Delay.Milliseconds(200);
            
            // Program Table
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nProgram Table\r\nValidating AttributeEqual (InnerText='Federal Assistance Programs') on item 'Login1.FormInlinePanelHeading.FederalAssistancePrograms'.", repo.Login1.FormInlinePanelHeading.FederalAssistanceProgramsInfo, new RecordItemIndex(9));
                Validate.AttributeEqual(repo.Login1.FormInlinePanelHeading.FederalAssistanceProgramsInfo, "InnerText", "Federal Assistance Programs", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            // Program Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(10));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 12;9.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(11));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("12;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value $RPM_Admin_WM. Associated repository item: 'Login1.HiChandlerBing'", repo.Login1.HiChandlerBingInfo, new RecordItemIndex(12));
            repo.Login1.HiChandlerBingInfo.WaitForAttributeEqual(5000, "InnerText", RPM_Admin_WM);
            
            // Projects
            Report.Log(ReportLevel.Info, "Section", "Projects", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NgScope.Projects' at 70;14.", repo.Login1.NgScope.ProjectsInfo, new RecordItemIndex(15));
            repo.Login1.NgScope.Projects.Click("70;14");
            Delay.Milliseconds(200);
            
            // Project Table
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nProject Table\r\nValidating AttributeEqual (InnerText='Federal Assistance Projects') on item 'Login1.FormInlinePanelHeading.FederalAssistanceProjects'.", repo.Login1.FormInlinePanelHeading.FederalAssistanceProjectsInfo, new RecordItemIndex(16));
                Validate.AttributeEqual(repo.Login1.FormInlinePanelHeading.FederalAssistanceProjectsInfo, "InnerText", "Federal Assistance Projects", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(16)); }
            
            // Project Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(17));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 12;9.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(18));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("12;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value $RPM_Admin_WM. Associated repository item: 'Login1.HiChandlerBing'", repo.Login1.HiChandlerBingInfo, new RecordItemIndex(19));
            repo.Login1.HiChandlerBingInfo.WaitForAttributeEqual(5000, "InnerText", RPM_Admin_WM);
            
            // Themes
            Report.Log(ReportLevel.Info, "Section", "Themes", new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(21));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Themes') on item 'Login1.NgScope.Themes'.", repo.Login1.NgScope.ThemesInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.Login1.NgScope.ThemesInfo, "InnerText", "Themes");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NgScope.Themes' at 34;11.", repo.Login1.NgScope.ThemesInfo, new RecordItemIndex(23));
            repo.Login1.NgScope.Themes.Click("34;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Themes') on item 'Login1.FormInlinePanelHeading.Themes'.", repo.Login1.FormInlinePanelHeading.ThemesInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.Login1.FormInlinePanelHeading.ThemesInfo, "InnerText", "Themes");
            Delay.Milliseconds(100);
            
            // Theme Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(25));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 12;9.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(26));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("12;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value $RPM_Admin_WM. Associated repository item: 'Login1.HiChandlerBing'", repo.Login1.HiChandlerBingInfo, new RecordItemIndex(27));
            repo.Login1.HiChandlerBingInfo.WaitForAttributeEqual(5000, "InnerText", RPM_Admin_WM);
            
            // Indicators
            Report.Log(ReportLevel.Info, "Section", "Indicators", new RecordItemIndex(28));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(29));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Indicators') on item 'Login1.NgScope.Indicators'.", repo.Login1.NgScope.IndicatorsInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.Login1.NgScope.IndicatorsInfo, "InnerText", "Indicators");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NgScope.Indicators' at 27;1.", repo.Login1.NgScope.IndicatorsInfo, new RecordItemIndex(31));
            repo.Login1.NgScope.Indicators.Click("27;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Indicators') on item 'Login1.FormInlinePanelHeading.Indicators'.", repo.Login1.FormInlinePanelHeading.IndicatorsInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.Login1.FormInlinePanelHeading.IndicatorsInfo, "InnerText", "Indicators");
            Delay.Milliseconds(100);
            
            // Indicator Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(33));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 12;9.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(34));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("12;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value $RPM_Admin_WM. Associated repository item: 'Login1.HiChandlerBing'", repo.Login1.HiChandlerBingInfo, new RecordItemIndex(35));
            repo.Login1.HiChandlerBingInfo.WaitForAttributeEqual(5000, "InnerText", RPM_Admin_WM);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
