///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R1_01_HomePage_Footer_DomesticGrantor_Administration recording.
    /// </summary>
    [TestModule("41ffe6fb-a0ac-4251-bec8-66f415228330", ModuleType.Recording, 1)]
    public partial class R1_01_HomePage_Footer_DomesticGrantor_Administration : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_TSTRepository repository.
        /// </summary>
        public static Service_Portal_Regression_TSTRepository repo = Service_Portal_Regression_TSTRepository.Instance;

        static R1_01_HomePage_Footer_DomesticGrantor_Administration instance = new R1_01_HomePage_Footer_DomesticGrantor_Administration();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R1_01_HomePage_Footer_DomesticGrantor_Administration()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R1_01_HomePage_Footer_DomesticGrantor_Administration Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Footer Links
            Report.Log(ReportLevel.Info, "Section", "Footer Links", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            // Footer - Administration
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Administration\r\nValidating AttributeEqual (InnerText='Administration') on item 'Login.NgScope3.Administration'.", repo.Login.NgScope3.AdministrationInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Login.NgScope3.AdministrationInfo, "InnerText", "Administration", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            // Footer - Grantee Accounts
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Grantee Accounts\r\nValidating AttributeEqual (InnerText='Grantee Accounts') on item 'Login.NgScope3.GranteeAccounts'.", repo.Login.NgScope3.GranteeAccountsInfo, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.Login.NgScope3.GranteeAccountsInfo, "InnerText", "Grantee Accounts", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            // Footer - Organization Records
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Organization Records\r\nValidating AttributeEqual (InnerText='Organization Records') on item 'Login.NgScope3.OrganizationRecords'.", repo.Login.NgScope3.OrganizationRecordsInfo, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Login.NgScope3.OrganizationRecordsInfo, "InnerText", "Organization Records", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            // Footer - Pending User Registration
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Pending User Registration\r\nValidating AttributeEqual (InnerText='Pending User Registrations') on item 'Login.NgScope3.PendingUserRegistrations'.", repo.Login.NgScope3.PendingUserRegistrationsInfo, new RecordItemIndex(5));
                Validate.AttributeEqual(repo.Login.NgScope3.PendingUserRegistrationsInfo, "InnerText", "Pending User Registrations", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(6));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Grantee Accounts
            Report.Log(ReportLevel.Info, "Section", "Grantee Accounts", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.NgScope3.GranteeAccounts' at 70;14.", repo.Login.NgScope3.GranteeAccountsInfo, new RecordItemIndex(8));
            repo.Login.NgScope3.GranteeAccounts.Click("70;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(9));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Users') on item 'Login.FormInlinePanelHeading.Users'.", repo.Login.FormInlinePanelHeading.UsersInfo, new RecordItemIndex(10));
                Validate.AttributeEqual(repo.Login.FormInlinePanelHeading.UsersInfo, "InnerText", "Users", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            // Grantee Accounts Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(11));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login.NavNavbarNavSamsNavbarNav.ATagHome' at 71;63.", repo.Login.NavNavbarNavSamsNavbarNav.ATagHomeInfo, new RecordItemIndex(12));
            repo.Login.NavNavbarNavSamsNavbarNav.ATagHome.Click("71;63");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value 'Hi, Joey Tribbiani!'. Associated repository item: 'Login.HiJoeyTribbiani'", repo.Login.HiJoeyTribbianiInfo, new RecordItemIndex(13));
            repo.Login.HiJoeyTribbianiInfo.WaitForAttributeEqual(5000, "InnerText", "Hi, Joey Tribbiani!");
            
            // Organization Records
            Report.Log(ReportLevel.Info, "Section", "Organization Records", new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(15));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.NgScope3.OrganizationRecords' at 70;14.", repo.Login.NgScope3.OrganizationRecordsInfo, new RecordItemIndex(16));
            repo.Login.NgScope3.OrganizationRecords.Click("70;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(17));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Companies') on item 'Login.FormInlinePanelHeading.Companies'.", repo.Login.FormInlinePanelHeading.CompaniesInfo, new RecordItemIndex(18));
                Validate.AttributeEqual(repo.Login.FormInlinePanelHeading.CompaniesInfo, "InnerText", "Companies", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(18)); }
            
            // Organization Records Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(19));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(20));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login.NavNavbarNavSamsNavbarNav.ATagHome' at 62;63.", repo.Login.NavNavbarNavSamsNavbarNav.ATagHomeInfo, new RecordItemIndex(21));
            repo.Login.NavNavbarNavSamsNavbarNav.ATagHome.Click("62;63");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value 'Hi, Joey Tribbiani!'. Associated repository item: 'Login.HiJoeyTribbiani'", repo.Login.HiJoeyTribbianiInfo, new RecordItemIndex(22));
            repo.Login.HiJoeyTribbianiInfo.WaitForAttributeEqual(5000, "InnerText", "Hi, Joey Tribbiani!");
            
            // Pending User Records
            Report.Log(ReportLevel.Info, "Section", "Pending User Records", new RecordItemIndex(23));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(24));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.NgScope3.PendingUserRegistrations' at 70;14.", repo.Login.NgScope3.PendingUserRegistrationsInfo, new RecordItemIndex(25));
            repo.Login.NgScope3.PendingUserRegistrations.Click("70;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(26));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='User Registration Requests') on item 'Login.FormInlinePanelHeading.UserRegistrationRequests'.", repo.Login.FormInlinePanelHeading.UserRegistrationRequestsInfo, new RecordItemIndex(27));
                Validate.AttributeEqual(repo.Login.FormInlinePanelHeading.UserRegistrationRequestsInfo, "InnerText", "User Registration Requests", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(27)); }
            
            // Pending User Records Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(28));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login.NavNavbarNavSamsNavbarNav.ATagHome' at 62;63.", repo.Login.NavNavbarNavSamsNavbarNav.ATagHomeInfo, new RecordItemIndex(29));
            repo.Login.NavNavbarNavSamsNavbarNav.ATagHome.Click("62;63");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value 'Hi, Joey Tribbiani!'. Associated repository item: 'Login.HiJoeyTribbiani'", repo.Login.HiJoeyTribbianiInfo, new RecordItemIndex(30));
            repo.Login.HiJoeyTribbianiInfo.WaitForAttributeEqual(5000, "InnerText", "Hi, Joey Tribbiani!");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
