///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R1_03_HomePage_TilesHeader_RPMGrantor_Planning recording.
    /// </summary>
    [TestModule("cd4f6f0a-a02b-44cb-85dd-d3e9eb21606f", ModuleType.Recording, 1)]
    public partial class R1_03_HomePage_TilesHeader_RPMGrantor_Planning : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_TSTRepository repository.
        /// </summary>
        public static Service_Portal_Regression_TSTRepository repo = Service_Portal_Regression_TSTRepository.Instance;

        static R1_03_HomePage_TilesHeader_RPMGrantor_Planning instance = new R1_03_HomePage_TilesHeader_RPMGrantor_Planning();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R1_03_HomePage_TilesHeader_RPMGrantor_Planning()
        {
            RPM_Grantor_WM = "Hi, Gunther Central-Perk!";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R1_03_HomePage_TilesHeader_RPMGrantor_Planning Instance
        {
            get { return instance; }
        }

#region Variables

        string _RPM_Grantor_WM;

        /// <summary>
        /// Gets or sets the value of variable RPM_Grantor_WM.
        /// </summary>
        [TestVariable("b66e7411-b33c-4391-bbce-81573adcdd55")]
        public string RPM_Grantor_WM
        {
            get { return _RPM_Grantor_WM; }
            set { _RPM_Grantor_WM = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Header Links
            Report.Log(ReportLevel.Info, "Section", "Header Links", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login1'.", repo.Login1.SelfInfo, new RecordItemIndex(1));
            repo.Login1.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Planning Tile
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nPlanning Tile\r\nValidating AttributeEqual (InnerText=' Planning ') on item 'Login1.NavNavbarNavSamsNavbarNav.ATagPlanning'.", repo.Login1.NavNavbarNavSamsNavbarNav.ATagPlanningInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Login1.NavNavbarNavSamsNavbarNav.ATagPlanningInfo, "InnerText", " Planning ", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            // Planning Tile
            Report.Log(ReportLevel.Info, "Mouse", "Planning Tile\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.ATagPlanning' at 109;58.", repo.Login1.NavNavbarNavSamsNavbarNav.ATagPlanningInfo, new RecordItemIndex(3));
            repo.Login1.NavNavbarNavSamsNavbarNav.ATagPlanning.Click("109;58");
            Delay.Milliseconds(200);
            
            // Planning -> Programs
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nPlanning -> Programs\r\nValidating AttributeEqual (InnerText='Programs') on item 'Login1.NavNavbarNavSamsNavbarNav.Programs1'.", repo.Login1.NavNavbarNavSamsNavbarNav.Programs1Info, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Login1.NavNavbarNavSamsNavbarNav.Programs1Info, "InnerText", "Programs", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            // Planning -> Projects
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nPlanning -> Projects\r\nValidating AttributeEqual (InnerText='Projects') on item 'Login1.NavNavbarNavSamsNavbarNav.Projects'.", repo.Login1.NavNavbarNavSamsNavbarNav.ProjectsInfo, new RecordItemIndex(5));
                Validate.AttributeEqual(repo.Login1.NavNavbarNavSamsNavbarNav.ProjectsInfo, "InnerText", "Projects", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            // Homepage Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(6));
            
            // Programs
            Report.Log(ReportLevel.Info, "Section", "Programs", new RecordItemIndex(7));
            
            // Planning -> Programs
            Report.Log(ReportLevel.Info, "Mouse", "Planning -> Programs\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.Programs1' at 59;23.", repo.Login1.NavNavbarNavSamsNavbarNav.Programs1Info, new RecordItemIndex(8));
            repo.Login1.NavNavbarNavSamsNavbarNav.Programs1.Click("59;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login1'.", repo.Login1.SelfInfo, new RecordItemIndex(9));
            repo.Login1.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Program Table
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nProgram Table\r\nValidating AttributeEqual (InnerText='Federal Assistance Programs') on item 'Login1.FederalAssistancePrograms'.", repo.Login1.FederalAssistanceProgramsInfo, new RecordItemIndex(10));
                Validate.AttributeEqual(repo.Login1.FederalAssistanceProgramsInfo, "InnerText", "Federal Assistance Programs", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            // Program Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(11));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 12;9.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(12));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("12;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value $RPM_Grantor_WM. Associated repository item: 'Login1.HiGuntherCentralPerk'", repo.Login1.HiGuntherCentralPerkInfo, new RecordItemIndex(13));
            repo.Login1.HiGuntherCentralPerkInfo.WaitForAttributeEqual(5000, "InnerText", RPM_Grantor_WM);
            
            // Projects
            Report.Log(ReportLevel.Info, "Section", "Projects", new RecordItemIndex(14));
            
            // Planning Tile
            Report.Log(ReportLevel.Info, "Mouse", "Planning Tile\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.ATagPlanning' at 87;67.", repo.Login1.NavNavbarNavSamsNavbarNav.ATagPlanningInfo, new RecordItemIndex(15));
            repo.Login1.NavNavbarNavSamsNavbarNav.ATagPlanning.Click("87;67");
            Delay.Milliseconds(200);
            
            // Planning -> Projects
            Report.Log(ReportLevel.Info, "Mouse", "Planning -> Projects\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.Projects' at 77;12.", repo.Login1.NavNavbarNavSamsNavbarNav.ProjectsInfo, new RecordItemIndex(16));
            repo.Login1.NavNavbarNavSamsNavbarNav.Projects.Click("77;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login1'.", repo.Login1.SelfInfo, new RecordItemIndex(17));
            repo.Login1.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Project Table
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nProject Table\r\nValidating AttributeEqual (InnerText='Federal Assistance Projects') on item 'Login1.FederalAssistanceProjects'.", repo.Login1.FederalAssistanceProjectsInfo, new RecordItemIndex(18));
                Validate.AttributeEqual(repo.Login1.FederalAssistanceProjectsInfo, "InnerText", "Federal Assistance Projects", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(18)); }
            
            // Project Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(19));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 12;9.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(20));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("12;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to equal the specified value $RPM_Grantor_WM. Associated repository item: 'Login1.HiGuntherCentralPerk'", repo.Login1.HiGuntherCentralPerkInfo, new RecordItemIndex(21));
            repo.Login1.HiGuntherCentralPerkInfo.WaitForAttributeEqual(5000, "InnerText", RPM_Grantor_WM);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
