///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R1_06_HomePage_Footer_OSGrantor_Administration recording.
    /// </summary>
    [TestModule("b256e349-5d65-4b42-aa28-91dcbb392b52", ModuleType.Recording, 1)]
    public partial class R1_06_HomePage_Footer_OSGrantor_Administration : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R1_06_HomePage_Footer_OSGrantor_Administration instance = new R1_06_HomePage_Footer_OSGrantor_Administration();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R1_06_HomePage_Footer_OSGrantor_Administration()
        {
            OSGrantor_WM = "Hi, Frank Buffay!";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R1_06_HomePage_Footer_OSGrantor_Administration Instance
        {
            get { return instance; }
        }

#region Variables

        string _OSGrantor_WM;

        /// <summary>
        /// Gets or sets the value of variable OSGrantor_WM.
        /// </summary>
        [TestVariable("6be11eba-aa45-40a4-87ae-e6a25d68fbe1")]
        public string OSGrantor_WM
        {
            get { return _OSGrantor_WM; }
            set { _OSGrantor_WM = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Footer Links
            Report.Log(ReportLevel.Info, "Section", "Footer Links", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Administration') on item 'Login1.NgScope1.Administration'.", repo.Login1.NgScope1.AdministrationInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Login1.NgScope1.AdministrationInfo, "InnerText", "Administration", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Grantee Accounts') on item 'Login1.NgScope1.GranteeAccounts'.", repo.Login1.NgScope1.GranteeAccountsInfo, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.Login1.NgScope1.GranteeAccountsInfo, "InnerText", "Grantee Accounts", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Organizations Records') on item 'Login1.NgScope1.OrganizationsRecords'.", repo.Login1.NgScope1.OrganizationsRecordsInfo, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Login1.NgScope1.OrganizationsRecordsInfo, "InnerText", "Organizations Records", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Pending User Registrations') on item 'Login1.NgScope1.PendingUserRegistrations'.", repo.Login1.NgScope1.PendingUserRegistrationsInfo, new RecordItemIndex(5));
                Validate.AttributeEqual(repo.Login1.NgScope1.PendingUserRegistrationsInfo, "InnerText", "Pending User Registrations", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            // Administration Footer Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(6));
            
            // Grantee Accounts
            Report.Log(ReportLevel.Info, "Section", "Grantee Accounts", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NgScope1.GranteeAccounts' at 62;10.", repo.Login1.NgScope1.GranteeAccountsInfo, new RecordItemIndex(8));
            repo.Login1.NgScope1.GranteeAccounts.Click("62;10");
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Users') on item 'Login1.FormInlinePanelHeading.Users'.", repo.Login1.FormInlinePanelHeading.UsersInfo, new RecordItemIndex(9));
                Validate.AttributeEqual(repo.Login1.FormInlinePanelHeading.UsersInfo, "InnerText", "Users", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            // Users Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 14;7.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(11));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("14;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'InnerText' to equal the specified value $OSGrantor_WM. Associated repository item: 'Login1.HiFrankBuffay'", repo.Login1.HiFrankBuffayInfo, new RecordItemIndex(12));
            repo.Login1.HiFrankBuffayInfo.WaitForAttributeEqual(10000, "InnerText", OSGrantor_WM);
            
            // Organization Records
            Report.Log(ReportLevel.Info, "Section", "Organization Records", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NgScope1.OrganizationsRecords' at 43;12.", repo.Login1.NgScope1.OrganizationsRecordsInfo, new RecordItemIndex(15));
            repo.Login1.NgScope1.OrganizationsRecords.Click("43;12");
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Companies') on item 'Login1.FormInlinePanelHeading.Companies'.", repo.Login1.FormInlinePanelHeading.CompaniesInfo, new RecordItemIndex(16));
                Validate.AttributeEqual(repo.Login1.FormInlinePanelHeading.CompaniesInfo, "InnerText", "Companies", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(16)); }
            
            // Companies Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 14;7.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(18));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("14;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'InnerText' to equal the specified value $OSGrantor_WM. Associated repository item: 'Login1.HiFrankBuffay'", repo.Login1.HiFrankBuffayInfo, new RecordItemIndex(19));
            repo.Login1.HiFrankBuffayInfo.WaitForAttributeEqual(10000, "InnerText", OSGrantor_WM);
            
            // Pending User Registration
            Report.Log(ReportLevel.Info, "Section", "Pending User Registration", new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(21));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NgScope1.PendingUserRegistrations' at 33;29.", repo.Login1.NgScope1.PendingUserRegistrationsInfo, new RecordItemIndex(22));
            repo.Login1.NgScope1.PendingUserRegistrations.Click("33;29");
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='User Registration Requests') on item 'Login1.FormInlinePanelHeading.UserRegistrationRequests'.", repo.Login1.FormInlinePanelHeading.UserRegistrationRequestsInfo, new RecordItemIndex(23));
                Validate.AttributeEqual(repo.Login1.FormInlinePanelHeading.UserRegistrationRequestsInfo, "InnerText", "User Registration Requests", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(23)); }
            
            // User Registration Requests Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.HOME' at 14;7.", repo.Login1.NavNavbarNavSamsNavbarNav.HOMEInfo, new RecordItemIndex(25));
            repo.Login1.NavNavbarNavSamsNavbarNav.HOME.Click("14;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'InnerText' to equal the specified value $OSGrantor_WM. Associated repository item: 'Login1.HiFrankBuffay'", repo.Login1.HiFrankBuffayInfo, new RecordItemIndex(26));
            repo.Login1.HiFrankBuffayInfo.WaitForAttributeEqual(10000, "InnerText", OSGrantor_WM);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
