///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R1_02_HomePage_Footer_DomesticGrantee_Support recording.
    /// </summary>
    [TestModule("0753aec0-5189-4a06-8438-9b79a93ec017", ModuleType.Recording, 1)]
    public partial class R1_02_HomePage_Footer_DomesticGrantee_Support : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_TSTRepository repository.
        /// </summary>
        public static Service_Portal_Regression_TSTRepository repo = Service_Portal_Regression_TSTRepository.Instance;

        static R1_02_HomePage_Footer_DomesticGrantee_Support instance = new R1_02_HomePage_Footer_DomesticGrantee_Support();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R1_02_HomePage_Footer_DomesticGrantee_Support()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R1_02_HomePage_Footer_DomesticGrantee_Support Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Footer Links
            Report.Log(ReportLevel.Info, "Section", "Footer Links", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Support') on item 'Login.NgScope3.Support'.", repo.Login.NgScope3.SupportInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Login.NgScope3.SupportInfo, "InnerText", "Support", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Grantee Training Resources') on item 'Login.NgScope3.GranteeTrainingResources'.", repo.Login.NgScope3.GranteeTrainingResourcesInfo, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.Login.NgScope3.GranteeTrainingResourcesInfo, "InnerText", "Grantee Training Resources", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Support') on item 'Login.NgScope3.Support1'.", repo.Login.NgScope3.Support1Info, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Login.NgScope3.Support1Info, "InnerText", "Support", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            // View Awards
            Report.Log(ReportLevel.Info, "Section", "View Awards", new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.NgScope3.GranteeTrainingResources' at 70;14.", repo.Login.NgScope3.GranteeTrainingResourcesInfo, new RecordItemIndex(6));
            repo.Login.NgScope3.GranteeTrainingResources.Click("70;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(7));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Src='https://mygrantstest.service-now.com/default_knowledge_base.svg') on item 'Login.HttpsMygrantstestServiceNowComDef'.", repo.Login.HttpsMygrantstestServiceNowComDefInfo, new RecordItemIndex(8));
                Validate.AttributeEqual(repo.Login.HttpsMygrantstestServiceNowComDefInfo, "Src", "https://mygrantstest.service-now.com/default_knowledge_base.svg", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(9));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Grantee Training Resources Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(10));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login.NavNavbarNavSamsNavbarNav.ATagHome' at 71;63.", repo.Login.NavNavbarNavSamsNavbarNav.ATagHomeInfo, new RecordItemIndex(11));
            repo.Login.NavNavbarNavSamsNavbarNav.ATagHome.Click("71;63");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'InnerText' to equal the specified value 'Hi, Rachel Green!'. Associated repository item: 'Login.HiRachelGreen'", repo.Login.HiRachelGreenInfo, new RecordItemIndex(12));
            repo.Login.HiRachelGreenInfo.WaitForAttributeEqual(30000, "InnerText", "Hi, Rachel Green!");
            
            // Support - TO BE CONTINUED
            Report.Log(ReportLevel.Info, "Section", "Support - TO BE CONTINUED", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
