///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R1_03_HomePage_Footer_RPMGrantor_Planning recording.
    /// </summary>
    [TestModule("c20cc2d5-1905-474e-9b7d-49f3f80d33dd", ModuleType.Recording, 1)]
    public partial class R1_03_HomePage_Footer_RPMGrantor_Planning : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_TSTRepository repository.
        /// </summary>
        public static Service_Portal_Regression_TSTRepository repo = Service_Portal_Regression_TSTRepository.Instance;

        static R1_03_HomePage_Footer_RPMGrantor_Planning instance = new R1_03_HomePage_Footer_RPMGrantor_Planning();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R1_03_HomePage_Footer_RPMGrantor_Planning()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R1_03_HomePage_Footer_RPMGrantor_Planning Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Footer Links
            Report.Log(ReportLevel.Info, "Section", "Footer Links", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(1));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            // Footer - Planning
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Planning\r\nValidating AttributeEqual (InnerText='Planning') on item 'Login.NgScope.Planning'.", repo.Login.NgScope.PlanningInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Login.NgScope.PlanningInfo, "InnerText", "Planning", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            // Footer - Programs
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Programs\r\nValidating AttributeEqual (InnerText='Programs') on item 'Login.NgScope.Programs'.", repo.Login.NgScope.ProgramsInfo, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.Login.NgScope.ProgramsInfo, "InnerText", "Programs", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            // Footer - Projects
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nFooter - Projects\r\nValidating AttributeEqual (InnerText='Projects') on item 'Login.NgScope.Projects'.", repo.Login.NgScope.ProjectsInfo, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Login.NgScope.ProjectsInfo, "InnerText", "Projects", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            // Planning Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(5));
            
            // Programs
            Report.Log(ReportLevel.Info, "Section", "Programs", new RecordItemIndex(6));
            
            // Footer - Programs
            Report.Log(ReportLevel.Info, "Mouse", "Footer - Programs\r\nMouse Left Click item 'Login.NgScope.Programs' at 34;7.", repo.Login.NgScope.ProgramsInfo, new RecordItemIndex(7));
            repo.Login.NgScope.Programs.Click("34;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(8));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Program Table
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nProgram Table\r\nValidating AttributeEqual (InnerText='Federal Assistance Programs') on item 'Login.FederalAssistancePrograms'.", repo.Login.FederalAssistanceProgramsInfo, new RecordItemIndex(9));
                Validate.AttributeEqual(repo.Login.FederalAssistanceProgramsInfo, "InnerText", "Federal Assistance Programs", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            // Program Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(10));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login.NavNavbarNavSamsNavbarNav.ATagHome' at 71;63.", repo.Login.NavNavbarNavSamsNavbarNav.ATagHomeInfo, new RecordItemIndex(11));
            repo.Login.NavNavbarNavSamsNavbarNav.ATagHome.Click("71;63");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(12));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Projects
            Report.Log(ReportLevel.Info, "Section", "Projects", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.NgScope.Projects' at 70;14.", repo.Login.NgScope.ProjectsInfo, new RecordItemIndex(15));
            repo.Login.NgScope.Projects.Click("70;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(16));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            // Project Table
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nProject Table\r\nValidating AttributeEqual (InnerText='Federal Assistance Projects') on item 'Login.FederalAssistanceProjects'.", repo.Login.FederalAssistanceProjectsInfo, new RecordItemIndex(17));
                Validate.AttributeEqual(repo.Login.FederalAssistanceProjectsInfo, "InnerText", "Federal Assistance Projects", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            // Project Table Screenshot
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(18));
            
            // Home Button
            Report.Log(ReportLevel.Info, "Mouse", "Home Button\r\nMouse Left Click item 'Login.NavNavbarNavSamsNavbarNav.ATagHome' at 62;63.", repo.Login.NavNavbarNavSamsNavbarNav.ATagHomeInfo, new RecordItemIndex(19));
            repo.Login.NavNavbarNavSamsNavbarNav.ATagHome.Click("62;63");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login'.", repo.Login.SelfInfo, new RecordItemIndex(20));
            repo.Login.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
