///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R3_01_Project_New_DomesticGrantor_Navigation recording.
    /// </summary>
    [TestModule("1a207973-decd-4540-ab8a-b20816fe5129", ModuleType.Recording, 1)]
    public partial class R3_01_Project_New_DomesticGrantor_Navigation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R3_01_Project_New_DomesticGrantor_Navigation instance = new R3_01_Project_New_DomesticGrantor_Navigation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R3_01_Project_New_DomesticGrantor_Navigation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R3_01_Project_New_DomesticGrantor_Navigation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 30;
            Delay.SpeedFactor = 1.00;

            Init();

            // Project Navigation
            Report.Log(ReportLevel.Info, "Section", "Project Navigation", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.ATagPlanning' at 61;41.", repo.Login1.NavNavbarNavSamsNavbarNav.ATagPlanningInfo, new RecordItemIndex(1));
            repo.Login1.NavNavbarNavSamsNavbarNav.ATagPlanning.Click("61;41");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.Projects' at 42;9.", repo.Login1.NavNavbarNavSamsNavbarNav.ProjectsInfo, new RecordItemIndex(2));
            repo.Login1.NavNavbarNavSamsNavbarNav.Projects.Click("42;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.FormInlinePanelHeading.NEW_FO' at 11;17.", repo.Login1.FormInlinePanelHeading.NEW_FOInfo, new RecordItemIndex(3));
            repo.Login1.FormInlinePanelHeading.NEW_FO.Click("11;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
