///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R4_01_FO_New_DomesticGrantor_Navigation recording.
    /// </summary>
    [TestModule("5b7edc0b-9d9b-4d05-996f-9dc12b2c048c", ModuleType.Recording, 1)]
    public partial class R4_01_FO_New_DomesticGrantor_Navigation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R4_01_FO_New_DomesticGrantor_Navigation instance = new R4_01_FO_New_DomesticGrantor_Navigation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R4_01_FO_New_DomesticGrantor_Navigation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R4_01_FO_New_DomesticGrantor_Navigation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 30;
            Delay.SpeedFactor = 1.00;

            Init();

            // Navigation to NEW Funding Opportunity
            Report.Log(ReportLevel.Info, "Section", "Navigation to NEW Funding Opportunity", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.ATagPreAward' at 92;49.", repo.Login1.NavNavbarNavSamsNavbarNav.ATagPreAwardInfo, new RecordItemIndex(1));
            repo.Login1.NavNavbarNavSamsNavbarNav.ATagPreAward.Click("92;49");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.FundingOpportunities' at 91;11.", repo.Login1.NavNavbarNavSamsNavbarNav.FundingOpportunitiesInfo, new RecordItemIndex(2));
            repo.Login1.NavNavbarNavSamsNavbarNav.FundingOpportunities.Click("91;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.FormInlinePanelHeading.NEW_FO' at 28;18.", repo.Login1.FormInlinePanelHeading.NEW_FOInfo, new RecordItemIndex(3));
            repo.Login1.FormInlinePanelHeading.NEW_FO.Click("28;18");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
