///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R5_01_App_New_DomesticGrantor_Navigation recording.
    /// </summary>
    [TestModule("0c9417ad-c875-4e24-a328-46a105efe107", ModuleType.Recording, 1)]
    public partial class R5_01_App_New_DomesticGrantor_Navigation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R5_01_App_New_DomesticGrantor_Navigation instance = new R5_01_App_New_DomesticGrantor_Navigation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R5_01_App_New_DomesticGrantor_Navigation()
        {
            Funding_Opportunity_Number = "SFOP0006111";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R5_01_App_New_DomesticGrantor_Navigation Instance
        {
            get { return instance; }
        }

#region Variables

        string _Funding_Opportunity_Number;

        /// <summary>
        /// Gets or sets the value of variable Funding_Opportunity_Number.
        /// </summary>
        [TestVariable("ea36d5d3-a154-468f-8125-24c6b995a73c")]
        public string Funding_Opportunity_Number
        {
            get { return _Funding_Opportunity_Number; }
            set { _Funding_Opportunity_Number = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 30;
            Delay.SpeedFactor = 1.00;

            Init();

            // Funding Opportunity Navigation
            Report.Log(ReportLevel.Info, "Section", "Funding Opportunity Navigation", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.ATagPreAward' at 79;48.", repo.Login1.NavNavbarNavSamsNavbarNav.ATagPreAwardInfo, new RecordItemIndex(1));
            repo.Login1.NavNavbarNavSamsNavbarNav.ATagPreAward.Click("79;48");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.FundingOpportunities' at 93;16.", repo.Login1.NavNavbarNavSamsNavbarNav.FundingOpportunitiesInfo, new RecordItemIndex(2));
            repo.Login1.NavNavbarNavSamsNavbarNav.FundingOpportunities.Click("93;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.FormInlinePanelHeading.DatatableSearch3' at 40;26.", repo.Login1.FormInlinePanelHeading.DatatableSearch3Info, new RecordItemIndex(3));
            repo.Login1.FormInlinePanelHeading.DatatableSearch3.Click("40;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Funding_Opportunity_Number'.", new RecordItemIndex(4));
            Keyboard.Press(Funding_Opportunity_Number);
            Delay.Milliseconds(30);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{tab}{enter}'.", new RecordItemIndex(5));
            Keyboard.Press("{tab}{enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'Login1'.", repo.Login1.SelfInfo, new RecordItemIndex(6));
            repo.Login1.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.NMKRanorexInternalTitle' at 69;56.", repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.NMKRanorexInternalTitleInfo, new RecordItemIndex(8));
            repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.NMKRanorexInternalTitle.Click("69;56");
            Delay.Milliseconds(200);
            
            // Navigate to Application
            Report.Log(ReportLevel.Info, "Section", "Navigate to Application", new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.ApplyHere' at 66;27.", repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.ApplyHereInfo, new RecordItemIndex(10));
            repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.ApplyHere.Click("66;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.SpanTagNewApplication'.", repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.SpanTagNewApplicationInfo, new RecordItemIndex(11));
            Validate.Exists(repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.SpanTagNewApplicationInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.ExpandAll' at 45;20.", repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.ExpandAllInfo, new RecordItemIndex(12));
            repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.ExpandAll.Click("45;20");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
