///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R6_01_FP_New_DomesticGrantor_RecipientInformation recording.
    /// </summary>
    [TestModule("8f88b9a5-d461-490b-b24a-edeb50fc1fa5", ModuleType.Recording, 1)]
    public partial class R6_01_FP_New_DomesticGrantor_RecipientInformation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R6_01_FP_New_DomesticGrantor_RecipientInformation instance = new R6_01_FP_New_DomesticGrantor_RecipientInformation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R6_01_FP_New_DomesticGrantor_RecipientInformation()
        {
            VendorRecipient_Contact = "Rachel Green";
            Type_of_Recipient = "U.S. Individual";
            Vendor_Recipient = "020651675";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R6_01_FP_New_DomesticGrantor_RecipientInformation Instance
        {
            get { return instance; }
        }

#region Variables

        string _VendorRecipient_Contact;

        /// <summary>
        /// Gets or sets the value of variable VendorRecipient_Contact.
        /// </summary>
        [TestVariable("20399cbf-2d05-4ae4-84e5-3b9665e24c4e")]
        public string VendorRecipient_Contact
        {
            get { return _VendorRecipient_Contact; }
            set { _VendorRecipient_Contact = value; }
        }

        string _Type_of_Recipient;

        /// <summary>
        /// Gets or sets the value of variable Type_of_Recipient.
        /// </summary>
        [TestVariable("1cf7b551-97e6-464a-9053-6c4c4ad673dd")]
        public string Type_of_Recipient
        {
            get { return _Type_of_Recipient; }
            set { _Type_of_Recipient = value; }
        }

        string _Vendor_Recipient;

        /// <summary>
        /// Gets or sets the value of variable Vendor_Recipient.
        /// </summary>
        [TestVariable("1ce723a0-c88b-4340-817d-5d1256301d76")]
        public string Vendor_Recipient
        {
            get { return _Vendor_Recipient; }
            set { _Vendor_Recipient = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 30;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1800 units.", new RecordItemIndex(0));
            Mouse.ScrollWheel(-1800);
            Delay.Milliseconds(500);
            
            // Vendor/Recipient
            Report.Log(ReportLevel.Info, "Section", "Vendor/Recipient", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.SpFormfieldCompanyStreet' at 100;54.", repo.Login1.SpFormfieldCompanyStreetInfo, new RecordItemIndex(2));
            repo.Login1.SpFormfieldCompanyStreet.Click("100;54");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}{Tab 11}{LShiftKey up}'.", new RecordItemIndex(3));
            Keyboard.Press("{LShiftKey down}{Tab 11}{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Vendor_Recipient'.", new RecordItemIndex(4));
            Keyboard.Press(Vendor_Recipient);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{enter}'.", new RecordItemIndex(6));
            Keyboard.Press("{enter}");
            Delay.Milliseconds(0);
            
            // Vendor/Recipient Contact
            Report.Log(ReportLevel.Info, "Section", "Vendor/Recipient Contact", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.SpFormfieldCompanyStreet' at 100;54.", repo.Login1.SpFormfieldCompanyStreetInfo, new RecordItemIndex(8));
            repo.Login1.SpFormfieldCompanyStreet.Click("100;54");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}{Tab 3}{LShiftKey up}'.", new RecordItemIndex(9));
            Keyboard.Press("{LShiftKey down}{Tab 3}{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$VendorRecipient_Contact'.", new RecordItemIndex(10));
            Keyboard.Press(VendorRecipient_Contact);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{enter}'.", new RecordItemIndex(12));
            Keyboard.Press("{enter}");
            Delay.Milliseconds(0);
            
            // Type of Recipient
            Report.Log(ReportLevel.Info, "Section", "Type of Recipient", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.SpFormfieldCompanyStreet' at 100;54.", repo.Login1.SpFormfieldCompanyStreetInfo, new RecordItemIndex(14));
            repo.Login1.SpFormfieldCompanyStreet.Click("100;54");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}{Tab}{LShiftKey up}'.", new RecordItemIndex(15));
            Keyboard.Press("{LShiftKey down}{Tab}{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Type_of_Recipient'.", new RecordItemIndex(16));
            Keyboard.Press(Type_of_Recipient);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(17));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{enter}'.", new RecordItemIndex(18));
            Keyboard.Press("{enter}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
