///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R6_01_FP_New_DomesticGrantor_Formfill_FinancialInfo recording.
    /// </summary>
    [TestModule("c96ebd2d-15f4-40ae-be69-67f4e451d26a", ModuleType.Recording, 1)]
    public partial class R6_01_FP_New_DomesticGrantor_Formfill_FinancialInfo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R6_01_FP_New_DomesticGrantor_Formfill_FinancialInfo instance = new R6_01_FP_New_DomesticGrantor_Formfill_FinancialInfo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R6_01_FP_New_DomesticGrantor_Formfill_FinancialInfo()
        {
            Statutory_Authority = "Fulbright-Hays";
            US_Share_of_Cost = "1000";
            Recipient_Share_of_Cost = "375";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R6_01_FP_New_DomesticGrantor_Formfill_FinancialInfo Instance
        {
            get { return instance; }
        }

#region Variables

        string _Statutory_Authority;

        /// <summary>
        /// Gets or sets the value of variable Statutory_Authority.
        /// </summary>
        [TestVariable("c9073810-89aa-428f-8920-1fd4f1210048")]
        public string Statutory_Authority
        {
            get { return _Statutory_Authority; }
            set { _Statutory_Authority = value; }
        }

        string _US_Share_of_Cost;

        /// <summary>
        /// Gets or sets the value of variable US_Share_of_Cost.
        /// </summary>
        [TestVariable("7213b9b5-95f2-41f4-9242-c87098f4c172")]
        public string US_Share_of_Cost
        {
            get { return _US_Share_of_Cost; }
            set { _US_Share_of_Cost = value; }
        }

        string _Recipient_Share_of_Cost;

        /// <summary>
        /// Gets or sets the value of variable Recipient_Share_of_Cost.
        /// </summary>
        [TestVariable("a39a39b4-015a-4802-81f2-301709877e50")]
        public string Recipient_Share_of_Cost
        {
            get { return _Recipient_Share_of_Cost; }
            set { _Recipient_Share_of_Cost = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 30;
            Delay.SpeedFactor = 1.00;

            Init();

            // Statutory Authority
            Report.Log(ReportLevel.Info, "Section", "Statutory Authority", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.UUsShareOfCost' at 440;18.", repo.Login1.UUsShareOfCostInfo, new RecordItemIndex(1));
            repo.Login1.UUsShareOfCost.Click("440;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}{Tab}{Tab}{LShiftKey up}' with focus on 'Login1.UUsShareOfCost'.", repo.Login1.UUsShareOfCostInfo, new RecordItemIndex(2));
            repo.Login1.UUsShareOfCost.PressKeys("{LShiftKey down}{Tab}{Tab}{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Statutory_Authority'.", new RecordItemIndex(3));
            Keyboard.Press(Statutory_Authority);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{enter}'.", new RecordItemIndex(5));
            Keyboard.Press("{enter}");
            Delay.Milliseconds(0);
            
            // U.S. Share of Cost
            Report.Log(ReportLevel.Info, "Section", "U.S. Share of Cost", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.UUsShareOfCost' at 440;18.", repo.Login1.UUsShareOfCostInfo, new RecordItemIndex(7));
            repo.Login1.UUsShareOfCost.Click("440;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Login1.UUsShareOfCost'.", repo.Login1.UUsShareOfCostInfo, new RecordItemIndex(8));
            Keyboard.PrepareFocus(repo.Login1.UUsShareOfCost);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$US_Share_of_Cost' with focus on 'Login1.UUsShareOfCost'.", repo.Login1.UUsShareOfCostInfo, new RecordItemIndex(9));
            repo.Login1.UUsShareOfCost.PressKeys(US_Share_of_Cost);
            Delay.Milliseconds(0);
            
            // Recipient Share of Cost
            Report.Log(ReportLevel.Info, "Section", "Recipient Share of Cost", new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.SpFormfieldURecipientShareOfCost' at 1042;19.", repo.Login1.SpFormfieldURecipientShareOfCostInfo, new RecordItemIndex(11));
            repo.Login1.SpFormfieldURecipientShareOfCost.Click("1042;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Login1.SpFormfieldURecipientShareOfCost'.", repo.Login1.SpFormfieldURecipientShareOfCostInfo, new RecordItemIndex(12));
            Keyboard.PrepareFocus(repo.Login1.SpFormfieldURecipientShareOfCost);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Recipient_Share_of_Cost' with focus on 'Login1.SpFormfieldURecipientShareOfCost'.", repo.Login1.SpFormfieldURecipientShareOfCostInfo, new RecordItemIndex(13));
            repo.Login1.SpFormfieldURecipientShareOfCost.PressKeys(Recipient_Share_of_Cost);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
