///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R6_01_FP_New_DomesticGrantor_FormFill_AwardAssignments recording.
    /// </summary>
    [TestModule("24f1db2d-46e3-4f2a-aaf8-5efa761e6ad1", ModuleType.Recording, 1)]
    public partial class R6_01_FP_New_DomesticGrantor_FormFill_AwardAssignments : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R6_01_FP_New_DomesticGrantor_FormFill_AwardAssignments instance = new R6_01_FP_New_DomesticGrantor_FormFill_AwardAssignments();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R6_01_FP_New_DomesticGrantor_FormFill_AwardAssignments()
        {
            Primary_Grants_Officer = "Ashley Higgins";
            Primary_Program_Officer = "Joey Tribbiani";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R6_01_FP_New_DomesticGrantor_FormFill_AwardAssignments Instance
        {
            get { return instance; }
        }

#region Variables

        string _Primary_Grants_Officer;

        /// <summary>
        /// Gets or sets the value of variable Primary_Grants_Officer.
        /// </summary>
        [TestVariable("21191957-e138-4974-9004-59a9992c3e21")]
        public string Primary_Grants_Officer
        {
            get { return _Primary_Grants_Officer; }
            set { _Primary_Grants_Officer = value; }
        }

        string _Primary_Program_Officer;

        /// <summary>
        /// Gets or sets the value of variable Primary_Program_Officer.
        /// </summary>
        [TestVariable("95ebb3d6-ac68-4baa-bdd3-d1b8a26c0629")]
        public string Primary_Program_Officer
        {
            get { return _Primary_Program_Officer; }
            set { _Primary_Program_Officer = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 30;
            Delay.SpeedFactor = 1.00;

            Init();

            // Primary Grants Officer
            Report.Log(ReportLevel.Info, "Section", "Primary Grants Officer", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.FO_Number' at 332;14.", repo.Login1.FO_NumberInfo, new RecordItemIndex(1));
            repo.Login1.FO_Number.Click("332;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab 4}'.", new RecordItemIndex(2));
            Keyboard.Press("{Tab 4}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Primary_Grants_Officer'.", new RecordItemIndex(3));
            Keyboard.Press(Primary_Grants_Officer);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{enter}'.", new RecordItemIndex(5));
            Keyboard.Press("{enter}");
            Delay.Milliseconds(0);
            
            // Primary Program Officer
            Report.Log(ReportLevel.Info, "Section", "Primary Program Officer", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.FO_Number' at 332;14.", repo.Login1.FO_NumberInfo, new RecordItemIndex(7));
            repo.Login1.FO_Number.Click("332;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab 9}'.", new RecordItemIndex(8));
            Keyboard.Press("{Tab 9}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Primary_Program_Officer'.", new RecordItemIndex(9));
            Keyboard.Press(Primary_Program_Officer);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{enter}'.", new RecordItemIndex(11));
            Keyboard.Press("{enter}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
