///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The R8_01_CC_All_DomesticGrantor_Navigation recording.
    /// </summary>
    [TestModule("35a6c852-e11d-4c0b-a043-7f154e8e6cf7", ModuleType.Recording, 1)]
    public partial class R8_01_CC_All_DomesticGrantor_Navigation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static R8_01_CC_All_DomesticGrantor_Navigation instance = new R8_01_CC_All_DomesticGrantor_Navigation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public R8_01_CC_All_DomesticGrantor_Navigation()
        {
            Application_Number = "SAPP0048104";
            NOA_Number = "SNOA0022724";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static R8_01_CC_All_DomesticGrantor_Navigation Instance
        {
            get { return instance; }
        }

#region Variables

        string _Application_Number;

        /// <summary>
        /// Gets or sets the value of variable Application_Number.
        /// </summary>
        [TestVariable("0230955d-573d-42c1-9757-542266a0bc6a")]
        public string Application_Number
        {
            get { return _Application_Number; }
            set { _Application_Number = value; }
        }

        string _NOA_Number;

        /// <summary>
        /// Gets or sets the value of variable NOA_Number.
        /// </summary>
        [TestVariable("a8420662-9a48-4d9f-a020-d71821d41c61")]
        public string NOA_Number
        {
            get { return _NOA_Number; }
            set { _NOA_Number = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 30;
            Delay.SpeedFactor = 1.00;

            Init();

            // NOA Search
            Report.Log(ReportLevel.Info, "Section", "NOA Search", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.ATagAward' at 73;48.", repo.Login1.NavNavbarNavSamsNavbarNav.ATagAwardInfo, new RecordItemIndex(1));
            repo.Login1.NavNavbarNavSamsNavbarNav.ATagAward.Click("73;48");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.NavNavbarNavSamsNavbarNav.Award' at 62;15.", repo.Login1.NavNavbarNavSamsNavbarNav.AwardInfo, new RecordItemIndex(2));
            repo.Login1.NavNavbarNavSamsNavbarNav.Award.Click("62;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.FormInlinePanelHeading.DatatableSearch6' at 66;26.", repo.Login1.FormInlinePanelHeading.DatatableSearch6Info, new RecordItemIndex(3));
            repo.Login1.FormInlinePanelHeading.DatatableSearch6.Click("66;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NOA_Number'.", new RecordItemIndex(4));
            Keyboard.Press(NOA_Number);
            Delay.Milliseconds(30);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{tab}{enter}'.", new RecordItemIndex(5));
            Keyboard.Press("{tab}{enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.NMKRanorexInternalTitle' at 36;5.", repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.NMKRanorexInternalTitleInfo, new RecordItemIndex(6));
            repo.Login1.C8d73b9a2db393b0016bc300f7c961903NgSco.NMKRanorexInternalTitle.Click("36;5");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
