///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Service_Portal_Regression_STG
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("873f5d65-a910-493d-8ed5-7e4342354905", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Service_Portal_Regression_STGRepository repository.
        /// </summary>
        public static Service_Portal_Regression_STGRepository repo = Service_Portal_Regression_STGRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Editable
            Report.Log(ReportLevel.Info, "Section", "Editable", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Login1.SpFormfieldUScoreString'.", repo.Login1.SpFormfieldUScoreStringInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.Login1.SpFormfieldUScoreString);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{delete}' with focus on 'Login1.SpFormfieldUScoreString'.", repo.Login1.SpFormfieldUScoreStringInfo, new RecordItemIndex(2));
            repo.Login1.SpFormfieldUScoreString.PressKeys("{delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'EDITABILITY TEST' with focus on 'Login1.SpFormfieldUScoreString'.", repo.Login1.SpFormfieldUScoreStringInfo, new RecordItemIndex(3));
            repo.Login1.SpFormfieldUScoreString.PressKeys("EDITABILITY TEST");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='EDITABILITY TEST') on item 'Login1.SpFormfieldUScoreString'.", repo.Login1.SpFormfieldUScoreStringInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.Login1.SpFormfieldUScoreStringInfo, "Value", "EDITABILITY TEST");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual (Value!='edt') on item 'Login1.SpFormfieldUScoreString'.", repo.Login1.SpFormfieldUScoreStringInfo, new RecordItemIndex(5));
            Validate.AttributeNotEqual(repo.Login1.SpFormfieldUScoreStringInfo, "Value", "edt");
            Delay.Milliseconds(0);
            
            // Read Only
            Report.Log(ReportLevel.Info, "Section", "Read Only", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login1.DivTagRow' at 442;255.", repo.Login1.DivTagRowInfo, new RecordItemIndex(7));
            repo.Login1.DivTagRow.Click("442;255");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Login1.SAMS'.", repo.Login1.SAMSInfo, new RecordItemIndex(8));
            Keyboard.PrepareFocus(repo.Login1.SAMS);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{delete}' with focus on 'Login1.SAMS'.", repo.Login1.SAMSInfo, new RecordItemIndex(9));
            repo.Login1.SAMS.PressKeys("{delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'EDITABILITY TEST' with focus on 'Login1.SAMS'.", repo.Login1.SAMSInfo, new RecordItemIndex(10));
            repo.Login1.SAMS.PressKeys("EDITABILITY TEST");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual (InnerText!='EDITABILITY TEST') on item 'Login1.SAMS'.", repo.Login1.SAMSInfo, new RecordItemIndex(11));
            Validate.AttributeNotEqual(repo.Login1.SAMSInfo, "InnerText", "EDITABILITY TEST");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
